name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_component: gke-gcloud-auth-plugin
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Build and push Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet
          docker build -t southamerica-east1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/cloud-demo/openjdk:17-jdk-alpine .
          docker push southamerica-east1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/cloud-demo/openjdk:17-jdk-alpine

      - name: Deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials gke-shared-des --region us-central1
          sed -i "s/GOOGLE_PROJECT/${{ secrets.GOOGLE_PROJECT_ID }}/g" deployment.yaml
          kubectl apply -f deployment.yaml