name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: install the gcloud cli
          uses: google-github-actions/setup-gcloud@v0
          with:
              project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
              service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
              export_default_credentials: true

        - name: Build and push Docker image
          env:
            GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT_ID }}
          run:
            gcloud auth configure-docker southamerica-east1-docker.pkg.dev
            docker build -t southamerica-east1-docker.pkg.dev/sonorous-zone-418311/cloud-demo/openjdk:17-jdk-alpine .
            docker push southamerica-east1-docker.pkg.dev/sonorous-zone-418311/cloud-demo/openjdk:17-jdk-alpine
